# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_url', models.CharField(max_length=300)),
                ('depth', models.IntegerField(default=1)),
                ('status', models.CharField(default='Started', max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='crawledimages',
            name='crawl_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.CrawlRequest'),
        ),
    ]
